### PR TITLE
Adding a zip archive with DICOM data to the notebook data repository.

### PR DESCRIPTION
**Pull request by zivy**

### CODE REVIEW

**Comment by blowekamp** [comment]
Is this data used anywhere yet?

**Comment by zivy** [comment]
Not yet. This is DICOM data of the abdominal phantom. The reason that I wanted to commit this now is that the experience with MIDAS and zip files was a bit painful and I wanted to document this (md5 changing every download and the url header missing expected content).

**Comment by blowekamp** [comment]
How would I reference a file contained in the zip?

**Comment by zivy** [comment]
This raise an issue I forgot about. Please see next pull request.

**Pull request merged**
