### PR TITLE
Fixed index out of bound bug

### PR DESCRIPTION
**Pull request by ervaibhavkumar**
Hi,

The last cell that is generating interactive python display is producing index out of bound error. So that is fixed in this commit.

Regards
Vaibhav

### CODE REVIEW

**Comment by zivy** [comment]
Thanks for the bugfix!

Please give me [write privileges to the pull request](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork). I had to clean the outputs and modify a link to an image so that it passes the tests.

**Comment by ervaibhavkumar** [comment]
@zivy  Allow edits from maintainers is already checked.
You can proceed towards editing.

**Comment by ervaibhavkumar** [comment]
@zivy  Tests are failing again.

**Comment by zivy** [comment]
@ervaibhavkumar 
Saw this. It is a different issue associated with the time it takes to do the data download. Working on it now. Once that is resolved I'll take care of the indexing bug.

**Pull request merged**
