### PR TITLE
Rnotebook - 2 new R notebooks mimicking the first two python ones

### PR DESCRIPTION
**Pull request by richardbeare**
These notebooks use my enhancements to SimpleITK and Swig that aren't yet in the main distributions of either.

### CODE REVIEW

**Comment by zivy** [comment]
Sorry for the delayed response.
I had to install an R environment on my system (OsX) and made the mistake of going the conda route. Currently this route has too many issues. Installed R from binary downloaded from CRAN.

Now to the point, I ran the notebooks and these are really nice additions to the repo as they show SimpleITK really supports R. Thank you Richard.

My only concern is with image reading. In Python we wrapped all the reading inside the fetch method which downloads from the web if the file is not available locally. There is no nice link we can point at to download all the data. Currently this is done in Python programmatically [fetch_data_all("Data", "Data/manifest.json"]. What would be the solution in R? Possibly a setup notebook that checks that simpleitk is installed and downloads all the relevant data like the Python setup notebook. 

Once we resolve this issue I'll merge the branch.

What are your thoughts?

**Comment by richardbeare** [comment]
Thanks - I'll have a look at the options.

I wasn't sure about the policy you had in mind - I was using data that I
included with the package, but that won't be enough for everything. I'll
see about mimicking the fetch_data_all function. My concern was that it
would require having the SimpleITK build directory available, which didn't
seem wise. I guess the other option is to put the manifest in the package.
I haven't check how you've done it with python, but let me know what you
prefer.

The other question is am I doing the right thing in committing only the
.pynb files? Should I also commit html renderings so that it is viewable on
github, or are you organising that later?

**Comment by zivy** [comment]
Not sure why you mentioned the SimpleITK build directory. This is not relevant to the data fetching. If you can use the same data we already use, that would be ideal. If you want to add data then let me know and I will add to the MIDAS repo where we host most of the data.

Our policy with regard to the notebook repo is to keep the data outside of the repository. The repository only contains code in the form of notebooks or Python modules/files. 

In general, we do data fetching in a lazy manner with data downloaded only when needed. This was a problem in a tutorial setting without internet access, so we also added the option of downloading everything in advance.

No need to commit html files, I will be working on automating their generation in the near future. I need to get rid of intentional errors we have in some notebooks as these stop the conversion to html.

**Comment by richardbeare** [comment]
Apologies - had assumed that the notebook data was the same as the simpleitk testing data. A lot of it probably is the same, but of course it is being fetched specifically for the notebooks. I have a download script in R that should do the job. Will update previous notebooks and use this approach in future.

**Comment by richardbeare** [comment]
Apologies - had assumed that the notebook data was the same as the simpleitk testing data. A lot of it probably is the same, but of course it is being fetched specifically for the notebooks. I have a download script in R that should do the job. Will update previous notebooks and use this approach in future.

**Comment by richardbeare** [comment]
I've updated the existing notebooks to use notebook data directory, and modified the viewer to better utilise the voxel spacing information.

See if it works OK for you.

**Comment by richardbeare** [comment]
I forgot to add - it uses the jsonlite package, available from cran

**Comment by zivy** [comment]
This is now generating an error when running the code 
cthead <- ReadImage(fetch_data("cthead1.png"))
cthead

--------------------------------------
Fetching  cthead1.png 

Error in if (tools::md5sum(outfile) == this.md5sum) {: missing value where TRUE/FALSE needed


Error in eval(expr, envir, enclos): object 'cthead' not found
--------------------------------------

Am I doing something wrong here? The file name is in the manifest.json file and I saw that you updated the default directory to "../Data" so the directory structure looks correct.

**Comment by richardbeare** [comment]
Do you have the environment variables for object store set? That is one
thing I haven't tested.

Otherwise, can you delete cthead and see if the fetch part works.

BTW - these notebooks do require the SimpleITK R interface built with my
modified swig, so not sure if you have that.

**Comment by richardbeare** [comment]
I've added some diagnostics, so could you give it another go?

I suspect I've made an error dealing with the environment variables, so it
would be handy if you could let me know how they look too.

**Comment by zivy** [comment]
I upgraded my OS to el capitan and at the same time all of the software I have installed so the downloaddata code is now working for me. I am getting an error message about Fiji/ImageJ which has to do with my java runtime. This is associated with the display of the ct slice and my environment variables. The data did download fine so now it is an issue with my specific environment which is ok.

Took me some time to learn a bit of R but I would like to suggest a possible alternative to the download script in R, the attached script, [ddata.txt](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/files/68728/ddata.txt), will invoke the Python code we already maintain. Only caveats are that it requires sourcing with chdir set to true and that the progress goes to the console and not to the notebook output. 

Let me know if this is a reasonable solution so that we have an easier time maintaining the code-base or if it is preferable to have the R implementation. If you are happy with this branch the way it is and do not intent to modify it, then once I get the notebooks working smoothly on my side I will merge the pull request.

**Comment by richardbeare** [comment]
I think it is probably best to hold of merging this for a while. I'm still
working on the best way to solve some garbage collection issues, and they
may end up influencing minor parts of the notebooks.

I didn't think I was using the imageJ viewing from the notebooks.

I'll look at the script - I guess my only worry at the moment is the
requirement for having both python and R available - a potential problem if
the R package ever ends up being available under windows.

**Comment by zivy** [comment]
You are not using imageJ explicitly. It appears that the notebook's default behavior when the "output" of the cell is an image is to try and display it:
library(SimpleITK)
source("downloaddata.R")
cthead <- ReadImage(fetch_data("cthead1.png"))
cthead

When I comment out the last row in the code above everything is fine, when the line is there the notebook attempts to launch Fiji/ImageJ. The viewer is not specified in an environment variable so I'm not sure why this specific viewer is launched by the notebook.

With regard to the concern of requiring both Python and R installed, this is a requirement of the Jupyter notebook project, see their [installation instructions](http://jupyter.readthedocs.org/en/latest/install.html#how-to-install-jupyter-notebook)

I will hold off on merging till you let me know that you are happy with the code after which I will test it again and merge.

**Comment by richardbeare** [comment]
Yes - default behaviour is to invoke "show", which is the imageJ stuff.
However I thought I'd replaced that in the notebook with a call to a
notebook friendly display - must have missed one.

Good news on python being always available for notebooks - should make
things simpler.

**Comment by zivy** [comment]
We have created a version of this branch that uses the rPython package to wrap the Python download code. This works with these notebooks and all of the functionality appears to work with SimpleITK's R wrapping. I will close this pull request and merge the branch from my fork of the repository. 

These notebooks are a great addition to SimpleITK, hopefully there are more to come.

**Pull request closed without merging**
