### PR TITLE
Add manual GA execution with testPyPi flag

### PR DESCRIPTION
**Pull request by jwj019**
This PR address issue https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/issues/283

### CODE REVIEW

**Comment by jwj019** [comment]
Tests seem to be failing due to marchingcubes.org going down.  Unsure if this is a temporary or permanent issue

**Comment by zivy** [comment]
Specific site was temporarily down, reran all workflows.

**Comment by blowekamp** [comment]
It looks like the CI is working now. 

@jwj019 After this is merged how can test.pypi be used for a CI test?

**Comment by jwj019** [comment]
@blowekamp If you go to https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/actions?query=workflow%3A%22Ubuntu+Pytest%22, you should see a "Run workflow" dropdown at the top.  There's a test PyPi option there.

**Pull request merged**
