### PR TITLE
Updated the "download data" instructions.

### PR DESCRIPTION
**Pull request by zivy**
The html did not match the instructions in the Readme.md, now it does.

### CODE REVIEW

**Comment by blowekamp** [comment]
How was this updated?

**Comment by blowekamp** [comment]
I have always just gone into settings and regenerated the page...

**Comment by zivy** [comment]
Not sure I understand your question. I manually edited the index.html. In any case, the section on downloading the data was still referring to the manual download from SPL and the visible human stuff. If the index.html is auto-generated from the readme.md then I guess you forgot to do it after you updated the readme.md.

**Comment by blowekamp** [comment]
OK, I will regenerate.

**Pull request closed without merging**
